#
# Copyright 2025-26 AESilky
# SPDX-License-Identifier: MIT License
#

.PHONY:	libs
libs:
	cd ctc;make
	cd diag;make
	cd disp;make
	cd sio;make
	cd util;make

.PHONY: clean
clean:
	cd ctc;make clean
	cd diag;make clean
	cd disp;make clean
	cd sio;make clean
	cd util;make clean

